#!/usr/bin/env python3
"""
generate_orca_input.py
======================
Post-docking QM/MM input generator for ORCA.

Usage:
    python generate_orca_input.py \
        --receptor receptor.pdbqt \
        --ligand   docked_out.pdbqt \
        --out      orca_qmmm.inp \
        [--qm_charge 0] [--qm_mult 1] \
        [--qm_radius 8.0] [--method "B3LYP def2-SVP"]

The script partitions the system into:
  QM  = ligand + protein residues with any heavy atom within --qm_radius Å
  MM  = remaining protein atoms (treated as point charges)

Output is a ready-to-run ORCA 5.x QM/MM input file using the ORCA-ONIOM
embedding scheme with the ChemShell interface, or standalone QM-only mode
(default) where the MM region is frozen as point charges.

Requirements: none (pure Python stdlib + optional numpy for distance calc)
"""

import argparse
import os
import sys
import math


# ---------------------------------------------------------------------------
# Minimal PDBQT parser
# ---------------------------------------------------------------------------

def parse_pdbqt(path):
    """Return list of atom dicts: {name, resname, chain, resnum, x, y, z, charge}."""
    atoms = []
    with open(path) as fh:
        for line in fh:
            rec = line[:6].strip()
            if rec not in ("ATOM", "HETATM"):
                continue
            try:
                atom = {
                    "record":  rec,
                    "serial":  int(line[6:11]),
                    "name":    line[12:16].strip(),
                    "resname": line[17:20].strip(),
                    "chain":   line[21:22].strip(),
                    "resnum":  int(line[22:26]),
                    "x":       float(line[30:38]),
                    "y":       float(line[38:46]),
                    "z":       float(line[46:54]),
                    "charge":  float(line[70:76]) if len(line) > 70 else 0.0,
                    "element": line[77:79].strip() if len(line) > 77 else "",
                    "raw":     line.rstrip(),
                }
                atoms.append(atom)
            except (ValueError, IndexError):
                pass
    return atoms


def dist(a, b):
    return math.sqrt((a["x"] - b["x"])**2 +
                     (a["y"] - b["y"])**2 +
                     (a["z"] - b["z"])**2)


def residue_key(atom):
    return (atom["chain"], atom["resnum"], atom["resname"])


# ---------------------------------------------------------------------------
# Partition into QM and MM regions
# ---------------------------------------------------------------------------

def partition(receptor_atoms, ligand_atoms, qm_radius):
    """Return (qm_protein_atoms, mm_atoms) based on proximity to ligand."""
    # Find residues with any heavy atom within qm_radius of any ligand heavy atom
    close_residues = set()
    lig_heavy = [a for a in ligand_atoms if not a["element"].upper().startswith("H")]
    rec_heavy = [a for a in receptor_atoms if not a["element"].upper().startswith("H")]

    for ra in rec_heavy:
        for la in lig_heavy:
            if dist(ra, la) <= qm_radius:
                close_residues.add(residue_key(ra))
                break

    qm_protein  = [a for a in receptor_atoms if residue_key(a) in close_residues]
    mm_atoms    = [a for a in receptor_atoms if residue_key(a) not in close_residues]
    return qm_protein, mm_atoms


# ---------------------------------------------------------------------------
# XYZ block writer (ORCA format)
# ---------------------------------------------------------------------------

def write_xyz_block(atoms, charge_label=False):
    lines = []
    for a in atoms:
        elem = a["element"] if a["element"] else a["name"][0]
        if charge_label:
            lines.append(f"  {elem:<4s}  {a['x']:12.6f}  {a['y']:12.6f}  {a['z']:12.6f}  Q {a['charge']:.4f}")
        else:
            lines.append(f"  {elem:<4s}  {a['x']:12.6f}  {a['y']:12.6f}  {a['z']:12.6f}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# ORCA input writer
# ---------------------------------------------------------------------------

def write_orca_input(out_path, qm_atoms, mm_atoms,
                     qm_charge, qm_mult, method):
    n_qm = len(qm_atoms)
    with open(out_path, "w") as fh:
        fh.write(f"# ORCA QM/MM input — generated by generate_orca_input.py\n")
        fh.write(f"# QM region: {n_qm} atoms  |  MM region (point charges): {len(mm_atoms)} atoms\n\n")

        fh.write(f"! {method} TightSCF NormalPrint\n\n")

        # Point charges from MM region (if any)
        if mm_atoms:
            pc_file = out_path.replace(".inp", "_mm.pc")
            fh.write(f"%pointcharges \"{os.path.basename(pc_file)}\"\n\n")
            with open(pc_file, "w") as pcf:
                pcf.write(f"{len(mm_atoms)}\n")
                for a in mm_atoms:
                    pcf.write(f"  {a['charge']:.4f}  {a['x']:.6f}  {a['y']:.6f}  {a['z']:.6f}\n")
            print(f"  Wrote MM point charges: {pc_file} ({len(mm_atoms)} atoms)")

        fh.write(f"* xyz {qm_charge} {qm_mult}\n")
        fh.write(write_xyz_block(qm_atoms))
        fh.write("\n*\n")

    print(f"  Wrote ORCA input: {out_path}")
    print(f"  QM region: {n_qm} atoms (charge={qm_charge}, mult={qm_mult})")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--receptor",   required=True,  help="receptor PDBQT")
    p.add_argument("--ligand",     required=True,  help="docked ligand PDBQT (first model used)")
    p.add_argument("--out",        default="orca_qmmm.inp", help="output ORCA .inp file")
    p.add_argument("--qm_charge",  type=int,   default=0,    help="total charge of QM region")
    p.add_argument("--qm_mult",    type=int,   default=1,    help="spin multiplicity of QM region")
    p.add_argument("--qm_radius",  type=float, default=8.0,  help="radius (Å) for QM region inclusion")
    p.add_argument("--method",     default="B3LYP def2-SVP D3BJ",
                   help="ORCA method/basis line (default: B3LYP def2-SVP D3BJ)")
    p.add_argument("--ligand2",    default=None,
                   help="optional second docked ligand for dual-ligand QM region")
    args = p.parse_args()

    print(f"Parsing receptor: {args.receptor}")
    receptor = parse_pdbqt(args.receptor)
    print(f"  {len(receptor)} atoms")

    print(f"Parsing ligand:   {args.ligand}")
    ligand = parse_pdbqt(args.ligand)
    print(f"  {len(ligand)} atoms")

    all_ligand = ligand[:]
    if args.ligand2:
        print(f"Parsing ligand2:  {args.ligand2}")
        ligand2 = parse_pdbqt(args.ligand2)
        print(f"  {len(ligand2)} atoms")
        all_ligand.extend(ligand2)

    qm_protein, mm_atoms = partition(receptor, all_ligand, args.qm_radius)
    print(f"QM protein residues selected within {args.qm_radius} Å: "
          f"{len(set(residue_key(a) for a in qm_protein))} residues, {len(qm_protein)} atoms")

    qm_all = all_ligand + qm_protein

    write_orca_input(args.out, qm_all, mm_atoms,
                     args.qm_charge, args.qm_mult, args.method)


if __name__ == "__main__":
    main()
